name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The repository has been cloned."
